import hashlib
import logging
import urllib.error
import urllib.request
from typing import Any

logger = logging.getLogger(__name__)


def check_password_breach(
    password: str, use_cache: bool = True
) -> tuple[bool, dict[str, Any]]:
    """
    Check if password has been breached using Have I Been Pwned API (k-anonymity).

    Returns:
        Tuple[bool, Dict]: (is_breached, details_dict)
        Details dict contains: message, count, hash_prefix, timestamp, recommendations
    """
    from datetime import datetime

    result = {
        "is_breached": False,
        "message": "",
        "count": 0,
        "hash_prefix": "",
        "timestamp": datetime.now().isoformat(),
        "recommendations": [],
        "error": None,
    }

    try:
        sha1_hash = hashlib.sha1(password.encode()).hexdigest().upper()  # nosec
        prefix = sha1_hash[:5]
        suffix = sha1_hash[5:]
        result["hash_prefix"] = prefix

        url = f"https://api.pwnedpasswords.com/range/{prefix}"

        try:
            with urllib.request.urlopen(url, timeout=5) as response:  # nosec
                data = response.read().decode("utf-8")

                for line in data.splitlines():
                    hash_suffix, count = line.split(":")
                    if hash_suffix == suffix:
                        count = int(count)
                        result["is_breached"] = True
                        result["count"] = count
                        result["message"] = (
                            f"Password has been breached ({count:,} times found in data breaches)"
                        )
                        result["recommendations"] = [
                            "This password has appeared in multiple data breaches",
                            "It should NOT be used for any account",
                            "Change this password immediately if currently in use",
                            "Use a strong, unique password generated by this tool",
                        ]
                        logger.warning(
                            f"Password found in breach database ({count} occurrences)"
                        )
                        return True, result

                result["is_breached"] = False
                result["message"] = "Password not found in any known breaches"
                result["recommendations"] = [
                    "This password is not in the Have I Been Pwned database",
                    "However, ensure it meets security requirements",
                    "Use a strong, unique password for each account",
                ]
                logger.info("Password not found in breach database")
                return False, result

        except urllib.error.URLError as e:
            error_msg = f"Unable to check breach database: {e}"
            result["error"] = str(e)
            result["message"] = error_msg
            result["recommendations"] = [
                "Could not connect to breach database",
                "Check your internet connection",
                "Try again later",
            ]
            logger.warning(f"Failed to check breach database: {e}")
            return False, result
        except TimeoutError:
            error_msg = "Breach check timed out"
            result["error"] = error_msg
            result["message"] = error_msg
            result["recommendations"] = [
                "Connection to breach database timed out",
                "Check your internet connection",
                "Try again later",
            ]
            logger.warning("Breach check timed out")
            return False, result
        except (ValueError, UnicodeDecodeError) as e:
            error_msg = f"Data encoding error: {e}"
            result["error"] = str(e)
            result["message"] = error_msg
            result["recommendations"] = [
                "Error processing breach check response",
                "Please try again",
            ]
            logger.error(f"Encoding error in breach check: {e}")
            return False, result

    except Exception as e:
        error_msg = f"Error checking breach: {e}"
        result["error"] = str(e)
        result["message"] = error_msg
        result["recommendations"] = [
            "An error occurred during breach check",
            "Please try again",
        ]
        logger.error(f"Error checking password breach: {e}")
        return False, result
